name: pg-monorepo

services:
  minio:
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_root_user
      MINIO_ROOT_PASSWORD: minio_root_password
      MINIO_BROWSER: on
    volumes:
      - minio_data:/bitnami/minio/data

  redis_cache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_cache_data:/data
    restart: unless-stopped

  pgvector_db:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    environment:
      POSTGRES_DB: pgvector_db
      POSTGRES_USER: pgvector_db
      POSTGRES_PASSWORD: pgvector_db
    # DATABASE_URL === postgres://pgvector_db:pgvector_db@db:5432/pgvector_db
    ports:
      - "5432:5432"
    volumes:
      - pgvector_db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql # init pgvector extension
    restart: always

  otel_lgtm:
    image: docker.io/grafana/otel-lgtm:latest
    ports:
      - "3111:3000" # Grafana UI
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    volumes:
      - ./container/grafana:/data/grafana
      - ./container/prometheus:/data/prometheus
      - ./container/loki:/data/loki
    environment:
      - GF_PATHS_DATA=/data/grafana
    env_file:
      - ./.env
    # stdin_open: true
    # tty: true

# Stores data outside the container to ensure persistence
volumes:
  minio_data:
  redis_cache_data: 
  pgvector_db_data: